"""Replace each task's environment/data/ with the messy CSVs + codebook
generated by `make_messy_data.py`. Idempotent.
"""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAMPLES = ROOT / "samples"
MESSY = ROOT / "_data_cache" / "_messy"

# Which messy files each NHANES-based task needs.
NHANES_TASKS = {
    "task_01_nhanes_obesity_prevalence":  ["demo_messy.csv", "bmx_messy.csv"],
    "task_02_nhanes_obesity_with_ci":     ["demo_messy.csv", "demo_supplement.csv", "bmx_messy.csv"],
    "task_03_nhanes_obesity_by_sex":      ["demo_messy.csv", "bmx_messy.csv"],
    "task_06_nhanes_sex_comparison":      ["demo_messy.csv", "demo_supplement.csv", "bmx_messy.csv", "bpx_messy.csv"],
    "task_09_nhanes_dietary_weights":     ["demo_messy.csv", "demo_supplement.csv", "dr1tot_messy.csv"],
    "task_10_nhanes_compound_subgroups":  ["demo_messy.csv", "demo_supplement.csv", "bmx_messy.csv"],
}

# Files that should always live in env/data/docs/ for messy NHANES tasks.
COMMON_DOCS = ["messy_codebook.md"]


def reset_data(task: str) -> None:
    data_dir = SAMPLES / task / "environment" / "data"
    if data_dir.exists():
        shutil.rmtree(data_dir)
    (data_dir / "docs").mkdir(parents=True, exist_ok=True)


def main():
    # NHANES messy tasks
    for task, files in NHANES_TASKS.items():
        reset_data(task)
        data_dir = SAMPLES / task / "environment" / "data"
        for f in files:
            shutil.copy(MESSY / f, data_dir / f)
        for d in COMMON_DOCS:
            shutil.copy(MESSY / d, data_dir / "docs" / d)
        # Preserve any task-specific docs (e.g. screenshots) by re-emitting
        # them from the canonical source where applicable.
        if task == "task_09_nhanes_dietary_weights":
            png = ROOT / "samples" / task / "environment" / "data" / "docs" / "dietary_methodology.png"
            if not png.exists():
                # Regenerate via the artifact script if needed.
                pass
        if task == "task_10_nhanes_compound_subgroups":
            # Severe obesity figure and sex coding figure no longer apply
            # (task is now concentration index). Still keep guidance file.
            md = SAMPLES / task / "environment" / "data" / "docs" / "nhanes_analytic_guidelines.md"
            md.write_text(
                "# NHANES analytic guidelines (excerpt)\n\n"
                "NHANES is a complex, stratified, multistage sample. The design "
                "variables are `design_stratum` (SDMVSTRA) and `design_psu` "
                "(SDMVPSU); use the codebook to identify the correct sample "
                "weight for your analysis.\n",
                encoding="utf-8",
            )
        if task == "task_06_nhanes_sex_comparison":
            md = SAMPLES / task / "environment" / "data" / "docs" / "nhanes_analytic_guidelines.md"
            md.write_text(
                "# NHANES analytic guidelines (excerpt)\n\n"
                "NHANES is a complex, stratified, multistage probability "
                "sample. Use `design_stratum` (SDMVSTRA) and `design_psu` "
                "(SDMVPSU) for design-adjusted variance via Taylor "
                "linearization. Strata with a single PSU drop out of the "
                "between-PSU variance term.\n",
                encoding="utf-8",
            )

    # NHIS task
    nhis_task = "task_05_nhis_chronic_pain_test"
    reset_data(nhis_task)
    data_dir = SAMPLES / nhis_task / "environment" / "data"
    shutil.copy(MESSY / "nhis_adult_messy.csv", data_dir / "nhis_adult_messy.csv")
    shutil.copy(MESSY / "messy_codebook.md", data_dir / "docs" / "messy_codebook.md")
    # Re-emit the chronic-pain doc.
    pain_md = data_dir / "docs" / "PAI_documentation.md"
    pain_md.write_text(
        (SAMPLES / nhis_task).joinpath("..", "..", "scripts", "pain_doc_template.md").read_text()
        if (SAMPLES / nhis_task).joinpath("..", "..", "scripts", "pain_doc_template.md").exists()
        else """# NHIS 2023 — chronic-pain and high-impact-pain documentation

## Variable: pain_freq_3mo (original PAIFRQ3M_A)

Universe: Sample Adults age 18+ who reported any pain.

Codes:
- 1 — Some days
- 2 — A few days
- 3 — Most days
- 4 — Every day
- 7 — Refused, 8 — Not ascertained, 9 — Don't know

**Chronic pain** = codes 3 or 4.

## Variable: pain_work_limit_3mo (original PAIWKLM3M_A)

Codes:
- 1 — Never
- 2 — Some days
- 3 — Most days
- 4 — Every day
- 7/8/9 — Refused / Not ascertained / Don't know

**High-impact pain** = codes 3 or 4 (most days or every day).

Restrict the denominator to respondents with valid (1-4) responses on
BOTH variables before computing anything.

## Variable: wt_sample_adult (original WTFA_A)

Analysis weight for all Sample Adult estimates. Records with weight = 0
should be excluded.

## Design variables

`design_stratum` (PSTRAT) and `design_psu` (PPSU) — use for design-
adjusted variance estimation.
""",
        encoding="utf-8",
    )

    print("done")


if __name__ == "__main__":
    main()
